# ----------------------------------------------------------------------
# Common configuration
# ----------------------------------------------------------------------
server:
  port: 8080

spring:
  application:
    name: bandsync
  banner:
    location: common/banner.txt

# ----------------------------------------------------------------------
# Development profile configuration
# ----------------------------------------------------------------------

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/bandsync
    username: bandsync
    password: bandsync

  jpa:
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always
      schema-locations: classpath:db/init/schema.sql
      data-locations: classpath:db/init/data.sql