# ----------------------------------------------------------------------
# Common configuration
# ----------------------------------------------------------------------
server:
  port: 8080

spring:
  application:
    name: bandsync
  banner:
    location: common/banner.txt

  jpa:
    show-sql: false
    defer-datasource-initialization: off
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
# ----------------------------------------------------------------------
# Development profile configuration
# ----------------------------------------------------------------------

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/bandsync_dev
    username: bandsync
    password: bandsync


  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-dev.yml

---
# ----------------------------------------------------------------------
# Production profile configuration
# ----------------------------------------------------------------------

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/bandsync
    username: bandsync
    password: bandsync


  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-prod.yml