# ----------------------------------------------------------------------
# Common configuration
# ----------------------------------------------------------------------
server:
  port: 8080

spring:
  application:
    name: bandsync
  banner:
    location: common/banner.txt

# ----------------------------------------------------------------------
# Development profile configuration
# ----------------------------------------------------------------------

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/bandsync
    username: bandsync
    password: bandsync

  jpa:
    show-sql: false
    defer-datasource-initialization: off
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml